# Generated by Django 4.0.5 on 2022-08-04 00:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_masdatosusuario_descripcion_masdatosusuario_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masdatosusuario',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
